### PR TITLE
gfx: Allow to resize game window

### PR DESCRIPTION
**Pull request by JIghtuse**
The game window looks *tiny* on HiDPI screens, so it would be nice to have ability to resize the window.

Image of Yaktocat

### CODE REVIEW

**Comment by cristicbz** [comment]
Thanks for the PR, really appreciate it! Sorry about the delay, I'm a bit short on time right now. Two thoughts though:
  1. You can aleady set the resolution through a command line flag (e.g. `target/release/rs_doom -r1920x1080`). Agreed, this is not ideal, but just making sure you knew about this.
  2. Doesn't your solution mess up the aspect ratio when you resize the window? It would be nice if we had an event handler for the resize events that updated the aspect ratio in the projection matrix.

That said, once I give this a try, I'll be happy to merge as is and work from there. Thanks again!

**Comment by JIghtuse** [comment]
No problem!
Oh, I didn't know it was possible to set resolution from command line.
Aspect ratio is managed by SDL and it scale window properly.

**Comment by cristicbz** [comment]
Apologies for the inexcusable delay. I'll merge and deal with aspect ratio in a separate PR (the projection matrix needs to be updated on resize, that's what I meant).

**Comment by cristicbz** [comment]
Thanks a lot for the contribution! I promise that any future PRs will get merged much more swiftly; I just went through christmas holidays and a job change.

**Comment by JIghtuse** [comment]
No problem! :smile_cat:

**Pull request merged**
